import BlogPage from '@/components/template/BlogPage'
import React from 'react'


export const metadata = {
    title: "وبلاگ|مکمل ورزشی",
    description: "Generated by create next app",
  };

function page() {
  return (
    <BlogPage />
  )
}

export default page